version: "3"
services:
  react-app:
    image: ruthvikc27/red-carpet-client
    stdin_open: true
    ports: 
      - "3000:3000"
    restart: always
    networks:
      - mern-app
  api-server:
    image: ruthvikc27/red-carpet-server
    ports:
      - "5000:5000"
    restart: always
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - C:\Users\ruthv\OneDrive\Documents\mongoDB\db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local